IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'FinanceLikeListSystem')
BEGIN
    CREATE DATABASE FinanceLikeListSystem;
END
GO

USE FinanceLikeListSystem;
GO

CREATE TABLE Users (
    UserId VARCHAR(11) PRIMARY KEY,
    UserName NVARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Account VARCHAR(50) NOT NULL UNIQUE,
    IsDeleted BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Products (
    No INT IDENTITY(1,1) PRIMARY KEY,
    ProductName NVARCHAR(100) NOT NULL,
    Price DECIMAL(18,4) NOT NULL,
    FeeRate DECIMAL(5,4) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE LikeLists (
    SN INT IDENTITY(1,1) PRIMARY KEY,
    UserId VARCHAR(11) NOT NULL FOREIGN KEY REFERENCES Users(UserId),
    ProductNo INT NOT NULL FOREIGN KEY REFERENCES Products(No),
    PurchaseQuantity INT NOT NULL,
    Account VARCHAR(50) NOT NULL,
    TotalFee DECIMAL(18,4) NOT NULL,
    TotalAmount DECIMAL(18,4) NOT NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);
