server.port=8080

spring.application.name=likelist-system

# 煩請測試時替換為實際資料庫帳號與密碼
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FinanceLikeListSystem;encrypt=false;trustServerCertificate=true;
spring.datasource.username=owner
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
